### ISSUE TITLE
2022年的劳动节假期中-4月30日，5月3日没有假期提醒

### ISSUE THREAD

**Issue by zealotCE** [lanceliao/china-holiday-calender#15]
感谢您的这个项目。
设备：iPhone 12
iOS版本：15.4 beta

----------
问题详情：
检查了一下，缺少了4月30日和5月3日的提醒内容。
具体见录屏。
https://user-images.githubusercontent.com/26129403/152956389-21fc60e6-b29e-4de5-8537-f7c50ec46844.mp4

**Comment by lanceliao** [comment]
这边测试了下是正常的，IOS 15.3.1
怀疑是beta系统的问题，但是群里另外以为朋友的15.4 beta也是正常的，建议更新正式版再测试一下

**Comment by zealotCE** [comment]
> 这边测试了下是正常的，IOS 15.3.1
> 怀疑是beta系统的问题，但是群里另外以为朋友的15.4 beta也是正常的，建议更新正式版再测试一下

好的，感谢。
