### ISSUE TITLE
全天补班可以弄成all day event 么

### ISSUE THREAD

**Issue by jchnxu** [lanceliao/china-holiday-calender#19]
要不然在month view下看不清，也容易被其他内容顶到后面去
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/4531670/160783683-4e90f4a7-b11c-4f4e-8919-2ac43937b267.png">

week view下，也会有很多overlap不太友好
<img width="152" alt="image" src="https://user-images.githubusercontent.com/4531670/160783949-4bdca0e4-39ea-4bf6-bc13-cb153f2283d0.png">

**Comment by onns** [comment]
https://onns.xyz/attachment/china-public-holiday.ics

**Comment by jchnxu** [comment]
已订阅！ 感谢！ @onns

**Comment by lanceliao** [comment]
README里面其实有说明怎么将补班设成全天事件的：
>补班日程可设置为全天事件，指定compStart=*并且compEnd=*即可
