### ISSUE TITLE
建议补班默认全天日程。

### ISSUE THREAD

**Issue by FriedrichTschen** [lanceliao/china-holiday-calender#28]
建议补班的默认设置为全天日程吧，不是所有人的工作时间都是早上9点至下午6点。

**Comment by yupunit** [comment]
> 

同意，希望更改，不是全天的日历会奇怪的变成这种
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/96571201/166672493-961e5fc1-e284-402b-bac6-65cade6544ec.png">

**Comment by onns** [comment]
https://github.com/lanceliao/china-holiday-calender/issues/19
