### ISSUE TITLE
建议加入非法定节假日，如母亲节等

### ISSUE THREAD

**Issue by zjmazy** [lanceliao/china-holiday-calender#29]
非常感谢开发者提供如此方便的日历订阅
如果能提供很多需要提前准备礼物的节日如：母亲节，父亲节，教师节等
就更好了，谢谢！

**Comment by ufoozhenghao** [comment]
支持

**Comment by ufoozhenghao** [comment]
支持 也可以将母亲节等添加到额外一个订阅上

**Comment by panxlhe** [comment]
支持！

**Comment by vicentory** [comment]
支持

**Comment by Charles94jp** [comment]
希望能加上不放假的传统节日，比如元宵节。再加上二十四节气

**Comment by huangheLee** [comment]
同意， 正是为了找母亲节这种  才用第三方的订阅， 不然苹果官方的就够用了

**Comment by onns** [comment]
https://onns.xyz/attachment/958ce5f28ff7a8f1c04396347c9c77b7.ics

**Comment by lanceliao** [comment]
我觉得这些非法定节假日比较难统一需求，例如有人需要母亲节、父亲节、教师节这些，而有的人可能会想要圣诞节甚至情人节之类。

**Comment by PeterChen1997** [comment]
确实是，感觉可以提供一个 list 组合订阅吧，上面这个 onns 的不错，感谢

**Comment by gitupdate** [comment]
> 非常感谢开发者提供如此方便的日历订阅 如果能提供很多需要提前准备礼物的节日如：母亲节，父亲节，教师节等 就更好了，谢谢！

用 柯基日历订阅,  `https://rili.callmekeji.com/calendar/keji_calendar.ics`

![image](https://github.com/lanceliao/china-holiday-calender/assets/92412374/9fe0acda-83a2-4b57-b444-edba00284db5)
