### ISSUE TITLE
2024年的假期出来了

### ISSUE THREAD

**Issue by guohui-ma** [lanceliao/china-holiday-calender#38]

**Comment by leo-of-hn** [comment]
很好奇，现在更新了2024年假期，Google日历上已经订阅了 会自己更新吗？还是说要手动再订阅一下

**Comment by guohui-ma** [comment]
得先等这个文件更新了、之后你的google日历就自动更新了。

**Comment by txzpro** [comment]
作者已经不维护了吧

**Comment by guohui-ma** [comment]
@txzpro 我看没说不维护啊？行吧，不维护了就算了。

**Comment by lanceliao** [comment]
已更新 https://github.com/lanceliao/china-holiday-calender/commit/2aa39ac8c6d5114ab8058f5dc59f6d7b575dad82
