### ISSUE TITLE
使用python的ics模块解析时报ValueError: A VALARM must have at least one DESCRIPTION

### ISSUE THREAD

**Issue by f1ynng8** [lanceliao/china-holiday-calender#42]
报错信息：
ValueError: A VALARM must have at least one DESCRIPTION

gpt解释：
VALARM是iCalendar规范的一部分，用于定义一个闹钟组件。根据规范，VALARM必须至少包含一个DESCRIPTION属性。

如果你在解析.ics文件时遇到了ValueError: A VALARM must have at least one DESCRIPTION这个错误，那可能是因为你的.ics文件中的VALARM组件没有包含DESCRIPTION属性。

**Comment by f1ynng8** [comment]
暂时先通过文本处理删除了所有的VALARM组件来供本地解析使用，希望作者能够在VALARM中添加DESCRIPTION。

**Comment by lanceliao** [comment]
感谢反馈，已修复
