### ISSUE TITLE
ios17不会在界面上显示班或者调休了2024年的

### ISSUE THREAD

**Issue by SiMaLaoShi** [lanceliao/china-holiday-calender#46]
![53d487ce5810d44d96cd33947f0eedd](https://github.com/lanceliao/china-holiday-calender/assets/28924681/d18f60cf-f174-451c-8f1d-3408050f34ab)
![4545fa0721c2a57ec099899e7029a95](https://github.com/lanceliao/china-holiday-calender/assets/28924681/09717a20-4d3a-4593-994e-a32730832e14)

**Comment by codinged** [comment]
我也不显示了~ 需要点进去才显示

**Comment by codinged** [comment]
@SiMaLaoShi 在wb找到一个方法   进设置-通用-
语言与地区。地区那里改下其他任意国家
再改回中国大陆重新打开日历就默认刷新了
亲测可用

**Comment by SiMaLaoShi** [comment]
> @SiMaLaoShi 在wb找到一个方法 进设置-通用- 语言与地区。地区那里改下其他任意国家 再改回中国大陆重新打开日历就默认刷新了 亲测可用

我这不行的， 用了一个快捷指令修复了

**Comment by LegionC** [comment]
> > @SiMaLaoShi 在wb找到一个方法 进设置-通用- 语言与地区。地区那里改下其他任意国家 再改回中国大陆重新打开日历就默认刷新了 亲测可用
> 
> 我这不行的， 用了一个快捷指令修复了

什么快捷指令，求教。

**Comment by lijun816** [comment]
> > @SiMaLaoShi 在wb找到一个方法 进设置-通用- 语言与地区。地区那里改下其他任意国家 再改回中国大陆重新打开日历就默认刷新了 亲测可用
> 
> 我这不行的， 用了一个快捷指令修复了

求快捷指令，被困扰的不行了

**Comment by SiMaLaoShi** [comment]
> > > @SiMaLaoShi 在wb找到一个方法 进设置-通用- 语言与地区。地区那里改下其他任意国家 再改回中国大陆重新打开日历就默认刷新了 亲测可用
> > 
> > 
> > 我这不行的， 用了一个快捷指令修复了
> 
> 求快捷指令，被困扰的不行了

https://www.icloud.com/shortcuts/d9be2a912ea24dfa9c23aa29cbbb0374

**Comment by LegionC** [comment]
> > > > @SiMaLaoShi 在wb找到一个方法 进设置-通用- 语言与地区。地区那里改下其他任意国家 再改回中国大陆重新打开日历就默认刷新了 亲测可用
> > > 
> > > 
> > > 我这不行的， 用了一个快捷指令修复了
> > 
> > 
> > 求快捷指令，被困扰的不行了
> 
> https://www.icloud.com/shortcuts/d9be2a912ea24dfa9c23aa29cbbb0374

谢谢，好像还是不好使，但是谢谢

**Comment by LegionC** [comment]
大家好，好像苹果自带的那个也可以显示了，并且在日历那个界面，点进去，下拉刷新后，就可以在界面上显示。
![1babb8954deb253e38be4f018860543](https://github.com/lanceliao/china-holiday-calender/assets/20474542/302d7e6d-09ae-45f3-b578-b0aeea8117dd)
![ed5da28f8b0639214994b8d71f042e5](https://github.com/lanceliao/china-holiday-calender/assets/20474542/75df9d17-3d98-408c-94aa-d0d1650c73e7)
