### ISSUE TITLE
需要一个只有上班没有放假事件的年度离线版本

### ISSUE THREAD

**Issue by ivysrono** [lanceliao/china-holiday-calender#5]
能开源制作方法也很好。

Android原生也有法定工作日闹钟的需求，目前可以稳定通过日历无限通知实现，不用扯到闹钟上。

这样设置成有事项就提醒，没事项就没提醒了，所以不需要标注放假。

同时可能有自行请假等情况，需要删除特定日期的事件实现自定义，所以需要不会联网更新。

以前都是我设置成全年上班，再手动删除周末和节假日的，所以希望能提供个自动生成的方法。

**Comment by onns** [comment]
你要啥格式的，我给你

**Comment by ivysrono** [comment]
2022年度，将全部法定工作日设置为一个连贯的事件，标题为“上班”或者“班”，假期全部留空没有事件即可。

**Comment by onns** [comment]
> 2022年度，将全部法定工作日设置为一个连贯的事件，标题为“上班”或者“班”，假期全部留空没有事件即可。

周一到周五上班，是一个事件？不是五个？

**Comment by ivysrono** [comment]
一个事件的重复才能实现统一修改提醒时间等信息吧

**Comment by lanceliao** [comment]
这个需求的个人定制化太强了，不符合这个日历项目简洁标准的初衷，您的这个需求可能需要自己写程序去实现才行。
