### ISSUE TITLE
FR：无调休日历

### ISSUE THREAD

**Issue by Wang-zhechao** [lanceliao/china-holiday-calender#50]
想问下有没有无调休假期的日历
example：
中秋节： 2024-9-17
国庆节：2024-10-1， 2024-10-2， 2024-10-3

**Comment by lanceliao** [comment]
有，请看README的说明

**Comment by Wang-zhechao** [comment]
![image](https://github.com/user-attachments/assets/eec7d3aa-3769-4367-80bd-9b4b7a1dbe23)
我指的是 无调休日历 元旦只有 1 月 1 日是假期  而非 3 天

**Comment by Wang-zhechao** [comment]
而非去除调休补班的日历
