### ISSUE TITLE
New Year's holiday adjustment information error(过年假日调休的信息是错误的)

### ISSUE THREAD

**Issue by p5ydn0** [lanceliao/china-holiday-calender#9]

**Comment by lanceliao** [comment]
能不能具体描述下是什么问题呢

**Comment by p5ydn0** [comment]
> 能不能具体描述下是什么问题呢

I just confirmed. Sorry, I was wrong. I see make-up work as a vacation. terribly sorry!（我刚确认了。对不起，是我看错了。我把补班看成了假期。非常抱歉！）
